#pragma once

// Flood Corridor helper for ROUTE_TYPE_TRANSPORT_FLOOD packets.
//
// A geo-corridor is a union of up to MAX_CORRIDOR_TRIPLES circles connected
// along a path.  It lets corridor-aware repeaters forward a flood only when
// their own position lies inside the corridor, giving the sender per-packet
// geographic scoping without pre-provisioned regions.
//
// Wire layout (Flood Corridor, "Model X"):
//   code_1 (transport_codes[0]) = transport code of the sender's corridor
//                                 region key, computed over the WIRE view
//                                 (corridor region included, see
//                                 TransportKey::calcTransportCode).  Default
//                                 key = well-known pseudo-region "corridor"
//                                 (auto-key from "#corridor"); a sender may
//                                 instead name a real region (companion
//                                 "corridor region" preference) so that
//                                 corridor-UNAWARE repeaters configured with
//                                 that region forward corridor packets
//                                 verbatim (blindly — they cannot geo-filter).
//   code_2 (transport_codes[1]) = extension registry word, see the registry
//                                 helpers below (type 0xC = corridor).
//   corridor region: N * CORRIDOR_TRIPLE_BYTES, carried in Packet::corridor[]
//                     (serialized between path and payload).  The payload stays
//                     the standard [channel_hash][MAC][ciphertext] — receivers
//                     are unaware of the corridor.
//
// Backward compatibility ("rolling deployment", wire view): corridor-unaware
// repeaters parse the corridor bytes as the front of the payload, so they
// compute code_1 over the very same byte string.  They never interpret
// code_2 (RegionMap::findMatch compares code_1 only), so the registry word is
// invisible to them.  An OLD repeater configured with a region matching
// code_1 — the auto-hashtag "corridor" (CLI: `region def corridor` +
// `region allowf corridor`, same SHA256("#corridor") key) or a real region
// the sender named — therefore matches and forwards corridor packets
// VERBATIM.  Old repeaters without a matching region still drop them at the
// region gate, and "allow Flood" never applies to transport floods.
//
// Wire encoding per triple (4 bytes / 32 bits):
//   Bits 31-18  lat_encoded  14-bit offset-binary  (lat +90)/180 × 16383
//   Bits 17- 4  lon_encoded  14-bit offset-binary  (lon+180)/360 × 16383
//   Bits  3- 0  radius_code  4-bit index into CORRIDOR_RADIUS_KM[]

#include <stdint.h>
#include <string.h>
#include <math.h>

#include <Packet.h>
#include <SHA256.h>
#include "TransportKeyStore.h"
#include "CorridorRadius.h"

// MAX_CORRIDOR_TRIPLES / CORRIDOR_TRIPLE_BYTES are defined in MeshCore.h
// (pulled in via Packet.h).

// --- Decoded representation ---

struct CorridorTriple {
    float lat;        // decimal degrees, -90..+90
    float lon;        // decimal degrees, -180..+180
    float radius_km;  // kilometres; CORRIDOR_RADIUS_UNLIMITED_KM means unlimited
};

// --- Encoding / Decoding ---

inline uint32_t encodeCorridorTriple(float lat, float lon, uint8_t radius_code) {
    uint16_t lat_enc = (uint16_t)((lat +  90.0f) / 180.0f * 16383.0f + 0.5f);
    uint16_t lon_enc = (uint16_t)((lon + 180.0f) / 360.0f * 16383.0f + 0.5f);
    if (lat_enc > 16383) lat_enc = 16383;
    if (lon_enc > 16383) lon_enc = 16383;
    return ((uint32_t)lat_enc << 18)
         | ((uint32_t)lon_enc <<  4)
         | ((uint32_t)(radius_code & 0x0F));
}

inline void decodeCorridorTriple(uint32_t encoded, CorridorTriple& out) {
    uint16_t lat_enc    = (uint16_t)((encoded >> 18) & 0x3FFF);
    uint16_t lon_enc    = (uint16_t)((encoded >>  4) & 0x3FFF);
    uint8_t  radius_code = (uint8_t)(encoded & 0x0F);
    out.lat       = (float)lat_enc / 16383.0f * 180.0f - 90.0f;
    out.lon       = (float)lon_enc / 16383.0f * 360.0f - 180.0f;
    out.radius_km = CORRIDOR_RADIUS_KM[radius_code];
}

// --- code_2 extension registry helpers ---
//
// code_2 (transport_codes[1]) layout for the corridor extension:
//   bits 15-12: extension type nibble — 0xC = corridor, 0x0 = none,
//               0xF = experimental (reserved), 0x1..0xB/0xE free for other
//               implementations (must be ignored opaquely by corridor firmware)
//   bits 11-10: corridor encoding version (0 = v0, the 4-byte triples below;
//               unknown versions are dropped cleanly — the triple size, and
//               with it the payload offset, cannot be determined)
//   bit  9:     FC — fail-closed: repeaters without their own position must
//               drop the packet (default 0 = fail-open, forward)
//   bit  8:     AU — corridor auto-generated by firmware (channel circle,
//               DM fallback, reply reversal), not user-defined (diagnostics /
//               future policy hint; no receiver behaviour in v0)
//   bit  7:     DZ — destination zone = last triple only (transport corridor);
//               else the whole corridor is the destination zone
//   bits  6-4:  reserved, senders MUST send 0, receivers ignore tolerantly
//   bits  3-0:  N — triple count (1..8)

#define CORRIDOR_EXT_TYPE_NONE         0x0
#define CORRIDOR_EXT_TYPE_CORRIDOR     0xC
#define CORRIDOR_EXT_TYPE_EXPERIMENTAL 0xF

// Policy flags for makeCorridorHeader()/fillCorridor() (not wire positions).
#define CORRIDOR_FLAG_FC   0x01   // fail-closed (code_2 bit 9)
#define CORRIDOR_FLAG_AU   0x02   // auto-generated (code_2 bit 8)
#define CORRIDOR_FLAG_DZ   0x04   // destination zone = last triple (code_2 bit 7)

// Extension type nibble of a raw code_2 value.
inline uint8_t getCorridorExtType(uint16_t code2) {
    return (uint8_t)((code2 >> 12) & 0x0F);
}

// True iff a raw code_2 value announces the corridor extension.
inline bool isCorridorExt(uint16_t code2) {
    return getCorridorExtType(code2) == CORRIDOR_EXT_TYPE_CORRIDOR;
}

// Corridor encoding version of a raw code_2 value (meaningful for type 0xC).
inline uint8_t getCorridorVer(uint16_t code2) {
    return (uint8_t)((code2 >> 10) & 0x03);
}

// Policy-flag decoders for a raw code_2 value (meaningful for type 0xC).
inline bool isCorridorFailClosed(uint16_t code2) { return (code2 & 0x0200) != 0; }
inline bool isCorridorAuto(uint16_t code2)       { return (code2 & 0x0100) != 0; }
inline bool isCorridorDestLastTriple(uint16_t code2) { return (code2 & 0x0080) != 0; }

// Extract the corridor triple count N from a raw code_2 value (0 for any
// non-corridor extension).
inline uint8_t getCorridorCount(uint16_t code2) {
    return isCorridorExt(code2) ? (uint8_t)(code2 & 0x0F) : 0;
}

// Build the code_2 extension word for a v0 corridor with n triples and the
// given CORRIDOR_FLAG_* policy flags.  n is clamped to MAX_CORRIDOR_TRIPLES.
inline uint16_t makeCorridorHeader(uint8_t n, uint8_t flags = 0) {
    if (n > MAX_CORRIDOR_TRIPLES) n = MAX_CORRIDOR_TRIPLES;
    uint16_t code2 = (uint16_t)(0xC000 | (n & 0x0F));
    if (flags & CORRIDOR_FLAG_FC) code2 |= 0x0200;
    if (flags & CORRIDOR_FLAG_AU) code2 |= 0x0100;
    if (flags & CORRIDOR_FLAG_DZ) code2 |= 0x0080;
    return code2;
}

inline float radiusCodeToKm(uint8_t code) {
    return CORRIDOR_RADIUS_KM[code & 0x0F];
}

// --- Pseudo-region "corridor" (Model X) ---

// The well-known corridor pseudo-region key, derived deterministically from the
// name "#corridor" exactly like an auto-hashtag region (SHA256 → 16 bytes).
// Sender and every corridor-aware repeater compute the same key → same code_1
// for a given payload.  No secret distribution; the key is public on purpose
// (code_1 is a routing tag, not access control).
inline const TransportKey& corridorPseudoKey() {
    static TransportKey key;
    static bool init = false;
    if (!init) {
        SHA256 sha;
        sha.update("#corridor", 9);
        sha.finalize(key.key, sizeof(key.key));
        init = true;
    }
    return key;
}

// True iff code_1 matches the corridor pseudo-region for this packet's wire
// view (corridor region + payload — the same byte string corridor-unaware
// firmware hashes, which is what makes the region-config compat path work).
inline bool matchesCorridorRegion(const mesh::Packet* pkt) {
    return pkt->transport_codes[0] == corridorPseudoKey().calcTransportCode(pkt);
}

// --- Packet region helpers ---

// Encode the given triples into pkt->corridor[] and write the v0 corridor
// extension word (N + policy flags) into code_2.  The packet's payload is
// left untouched (corridor is a separate region).  n is clamped to
// MAX_CORRIDOR_TRIPLES.  Each radius is rounded UP to the nearest supported
// table entry (so the encoded corridor always covers the requested one); use
// radius_km >= CORRIDOR_RADIUS_UNLIMITED_KM for "always inside".
inline void fillCorridor(mesh::Packet* pkt, const CorridorTriple* corridor, uint8_t n, uint8_t flags = 0) {
    if (pkt == nullptr) return;
    if (n > MAX_CORRIDOR_TRIPLES) n = MAX_CORRIDOR_TRIPLES;
    for (uint8_t i = 0; i < n; i++) {
        uint8_t radius_code = 15;  // default: unlimited
        if (corridor[i].radius_km < CORRIDOR_RADIUS_UNLIMITED_KM) {
            for (uint8_t r = 0; r < 15; r++) {
                if (CORRIDOR_RADIUS_KM[r] >= corridor[i].radius_km) { radius_code = r; break; }
            }
        }
        uint32_t encoded = encodeCorridorTriple(corridor[i].lat, corridor[i].lon, radius_code);
        memcpy(&pkt->corridor[i * CORRIDOR_TRIPLE_BYTES], &encoded, CORRIDOR_TRIPLE_BYTES);
    }
    pkt->transport_codes[1] = makeCorridorHeader(n, flags);
}

// Decode pkt->corridor[] into up to max triples.  Returns the count decoded
// (= pkt->getCorridorCount(), clamped to max).  No allocation.
inline uint8_t decodePacketCorridor(const mesh::Packet* pkt, CorridorTriple* out, uint8_t max) {
    uint8_t n = pkt->getCorridorCount();
    if (n > max) n = max;
    for (uint8_t i = 0; i < n; i++) {
        uint32_t encoded;
        memcpy(&encoded, &pkt->corridor[i * CORRIDOR_TRIPLE_BYTES], CORRIDOR_TRIPLE_BYTES);
        decodeCorridorTriple(encoded, out[i]);
    }
    return n;
}

// --- Spatial check ---

// True if the point lies inside the capsule between two circle centres, using
// the perpendicular distance to the segment and the linearly interpolated
// radius.  A cos(lat) correction scales longitude to ground distance.  An
// unlimited radius on either endpoint makes the whole segment always-inside.
// dist² is compared against r² (no sqrt).
inline bool pointInCorridorSegment(float lat, float lon,
                                   float c1lat, float c1lon, float r1,
                                   float c2lat, float c2lon, float r2)
{
    if (r1 >= CORRIDOR_RADIUS_UNLIMITED_KM || r2 >= CORRIDOR_RADIUS_UNLIMITED_KM) return true;
    float lat_mid = (c1lat + c2lat) * 0.5f;
    float cos_lat = cosf(lat_mid * (float)(M_PI / 180.0));
    float scale = 111.0f;  // 1 degree lat ≈ 111 km
    float vx = (c2lat - c1lat) * scale;
    float vy = (c2lon - c1lon) * cos_lat * scale;
    float wx = (lat - c1lat) * scale;
    float wy = (lon - c1lon) * cos_lat * scale;
    float len_sq = vx * vx + vy * vy;
    float t;
    if (len_sq < 1e-9f) {
        t = 0.0f;  // degenerate segment → treat as circle at c1
    } else {
        t = (wx * vx + wy * vy) / len_sq;
        if (t < 0.0f) t = 0.0f;
        else if (t > 1.0f) t = 1.0f;
    }
    float ax = c1lat * scale + t * vx;
    float ay = c1lon * cos_lat * scale + t * vy;
    float dx = lat * scale - ax;
    float dy = lon * cos_lat * scale - ay;
    float r = r1 + t * (r2 - r1);
    return (dx * dx + dy * dy) <= (r * r);
}

// True if point (lat, lon) lies inside the corridor = union of capsules along
// the polyline through the circle centres.
inline bool isPointInCorridor(float lat, float lon,
                              const CorridorTriple* circles, int count)
{
    if (count <= 0) return false;
    if (count == 1) {
        if (circles[0].radius_km >= CORRIDOR_RADIUS_UNLIMITED_KM) return true;
        return pointInCorridorSegment(lat, lon,
                                      circles[0].lat, circles[0].lon, circles[0].radius_km,
                                      circles[0].lat, circles[0].lon, circles[0].radius_km);
    }
    for (int i = 0; i < count - 1; ++i) {
        if (pointInCorridorSegment(lat, lon,
                                   circles[i].lat, circles[i].lon, circles[i].radius_km,
                                   circles[i + 1].lat, circles[i + 1].lon, circles[i + 1].radius_km)) {
            return true;
        }
    }
    return false;
}
